### ISSUE TITLE
Migrate visualisation tutorial to new book.

### ISSUE THREAD

**Issue by ryanrhymes** [owlbarn/owl_tutorials#1]
Before we have a new solution, current plplot is the default tool for plotting.

**Comment by mseri** [comment]
Then we need to make the figure geometry configurable and the labels should have the same color as the plot grid (right now labels are always red)

**Comment by mseri** [comment]
@ghennequin can we release the current `gp` on `opam` as `0.0.1`? I don't mind having to maintain updates to the tutorial for that, I think the graphical quality improvement is worth the effort

**Comment by ryanrhymes** [comment]
> Then we need to make the figure geometry configurable and the labels should have the same color as the plot grid (right now labels are always red)

Shall we consider to change default theme to black on white? I also find red on black looks rather odd.
