### ISSUE TITLE
Cleanup preludes and dependencies

### ISSUE THREAD

**Issue by mseri** [owlbarn/owl_tutorials#13]
We are inheriting lots of these from rwo, but we have different needs.

Currently in the various `prelude.ml` we start with 
```ocaml
#require "core,core.top,ppx_jane,owl-top,owl-plplot";;

open Core
open Owl
open Bigarray
```

I believe we should only use
```ocaml
#require "owl-top";;

open Owl
```

Sometimes we will need plplot as well but in general I think we can also omit that at first.

**Comment by mseri** [comment]
This may also reduce and simplify our duniverse attempt (still broken unfortunately)

**Comment by ryanrhymes** [comment]
Thank you for pointing it out, I have cleaned up the prelude.ml. Let me know in case I missed anything.
